name: play-tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '00 23 * * *'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest-playwright
          python -m pip install playwright

          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Ensure Playwright browsers are installed
        run: python -m playwright install chromium  
      
      - name: Test with pytest
        run: |
          python3 -m pytest -v --reruns 2 --browser chromium --alluredir=my_allure_results


 
